//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group8Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CandidateTable()
        {
            this.CandidatePolicies = new HashSet<CandidatePolicy>();
        }
    
        public int CandidateID { get; set; }
        public string CandidateName { get; set; }
        public string CandidateParty { get; set; }
        public Nullable<int> CandidateAge { get; set; }
        public string CandidateGender { get; set; }
        public string CandidatePicture { get; set; }
        public string CandidateWebsite { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidatePolicy> CandidatePolicies { get; set; }
    }
}
