//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group8Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidatePolicy
    {
        public int CandidatePolicyID { get; set; }
        public int PolicyID { get; set; }
        public int CandidateID { get; set; }
        public string PolicyDescription { get; set; }
    
        public virtual CandidateTable CandidateTable { get; set; }
        public virtual PolicyyTable PolicyyTable { get; set; }
    }
}
